@startuml
'https://plantuml.com/class-diagram

package config {
    class Crypto{
        - {static}PASSWORD: final char[]
        - {static} SALT: final byte[]
        - {static} base64Encode(bytes: byte[]): String
        - {static} base 64Decode(str: String): byte[]
        + {static} Encrypt(str : String): String
        + {static} Decrypt( str: String) : String
    }
    class LoadSet{
        + {static} loadSet(file: String, ask: boolean): String[]
        + {static} loadSet(file: String): String[]
    }

    class SaveSet{
        + savePW(pass:String, out: PrintStream): void

    }
    class Settings{
        - {static} p: Properties
        - {static} propertyFilename: final String
        + {static} IS_JAVA_1_6: boolean
        + {static} sshHostKeyVerificationFile: String
        + {static} defaultWidth : final String
        + {static} defaultHeight : final String
        + {static} defaultX : final String
        + {static} defaultY: final String
        + {static} maxConnections: in
        + {static} enableResuming: boolean
        + {static} enableUploadResuming: boolean
        + {static} noUploadResumingQuestion: boolean
        + {static} askToResume: boolean
        + {static} reconnect: boolean
        + {static} uiRefresh: int
        + {static} logFlushInterval: int
        + {static} useLogFlusher: boolean
        + {static} ftpTransferThreadPause: int
        + {static} smallSize: int
        + {static} smallSizeUp: int
        + {static} shortProgress: boolean
        + {static} defaultFtpPasvMode: String
        + {static} defaultEnableDebug: String
        + {static} FILL OUT THE REST - Left off on line 60
    }
}
package event {
    interface Acceptor{
        + accept(e: Event): void
    }
    abstract class Event{
        + {abstract} eventCode: int
    }
    class EventCollector implements Acceptor{
        # buffer: Vector
        + accept(e: Event): void
    }
    interface EventHandler{
        +handle(e:Event): boolean
    }
    class EventProcessor implements Runnable, Acceptor, FtpEventConstants, EventHandler{
        - {static} table: Hashtable
        - buffer: Vector
        - done: boolean
        + accept(e:Event): void
        + {static} addHandler(eventCode: int, h: EventHandler): void
        + handle(e:Event): boolean
        + run(): void
    }
    class FtpEvent extends Event{
        - code: int
        - message: String
        + eventMsg(): String
        + eventCode(): int
    }
    interface FtpEventConstants {
        + {static} FTPCommand: final int
        + {static} FTPPrompt: final int
        + {static} FTPShutdown: final int
    }
    class FtpEventHandler implements EventHandler{
       -{static} commands: ArrayList
       - client: FtpClient
       - methods: Hashtable
       + open(args:Vector): void
       + disconnect(args:Vector): void
       + cd(args: Vector): void
       + pwd(args: Vector): void
       + get(args: Vector): void
       + put(args: Vector): void
       + quit(args: Vector): void
       + handle(e: Event): boolean

    }
}
package gui{
    package base{
        package dir{
            class ColoredCellRenderer
            interface Dir
            class DirCanvas
            class DirCellRenderer extends DefaultListCellRenderer
            class DirComponent extends DirPanel implements ListSelectionListener
            class DirEntry
            class DirLister implements ActionListener
            class DirPanel extends HPanel implements Dir
            class MaterializedTableModel extends AbstractTableModel
            class TableUtils
        }
        class AppMenuBar
        class DownloadList
        class DownloadQueue
        class FtpHost
        class LocalDir
        class LogFlusher
        class Properties
        class RemoteDir
        class ResumeDialog
        class StatusCanvas
        class StatusPanel
        class UITool
        class UIUtils{
        class Spawn
        class UIUtils
        }
    }
    package framework{
        class BorderPanel
        class FileTransferable
        class GUIDefaults
        class HButton
        class HComboBox
        class HDesktopBackground
        class HFrame
        class HImage
        class HImageButton
        class HInsetPanel
        class HPanel
        class HPasswordField
        class HTextField
        class LoadPanel
        class ProgressbarItem
        class ProgressBarList
        class Template
        class TransferComponent
        class Updater

    }
    package hostchooser{
        class HostChooser
        class NfsHostChooser
        class SftpHostChooser
        class SmbHostChooser
        class WebdavHostChooser
    }
    package tasks{
       class AddBookmarks
               class AdvancedOptions
               class AutoRemover
               class BookmarkManager
               class Creator
               class Displayer
               class ExternalDisplayer
               class HostInfo
               class HostList
               class HttpBrowser
               class HttpDownloader
               class ImageViewer
               class LastConnections
               class NameChooser
               class NativeHttpBrowser
               class PathChanger
               class ProxyChooser
               class RemoteCommand
               class Remover
               class RemoverQuery
               class Renamer
    }
}
package net{
    package servers{
        class FtpServer
        class FtpServerSocket
    }
    package wrappers{
        class HttpTransfer
        class NfsConnection
        class Sftp2Connection{
            class MyUserInfo
            class Sftp2Connection
        }
        class Sftp2Transfer
        class Sftp2URLConnection
        class SmbConnection
        class SmbTest
        class SmbTransfer
        class StartConnection
        class WebdavConnection
    }
    interface BasicConnection
    class ConnectionHandler
    interface ConnectionListener
    class DataConnection
    class FilesystemConnection
    class FtpClient
    class FtpConnection
    interface FtpConstants
    class FtpKeepAliveThread
    class FtpTransfer
    class FtpURLConnection
    class FtpURLStreamHandler
    class JConnection
    class Transfer
}
package system{
    package logging{
        class Log
        class Log4Logger
        interface Logger
        class SystemLogger
    }
    class CommandLine
    class LocalIO
    class StringUtils
    class UpdateDaemon
}
package tools{
    class FileSearch{
        class FileSearch
        class Getter
    }
    class HttpSpider{
        class Holer
        class HttpSpider
    }
    class RSSFeeder
    class RSSParser
    class Shell
}
package util{
    class JHostChooser
    class JRawConnection
    class JReciever
    class RawConnection
    class ZipFileCreator
}
class JFtp
class JFtpApplet

JFtp --> Dir
JFtp --> DownloadList
JFtp --> HostInfo
JFtp --> ConnectionHandler
JFtp --> AppMenuBar
JFtp -.-> LocalDir
JFtp -.-> StatusPanel

JFtpApplet -.-> Settings


LoadSet -.-> Settings
LoadSet -.-> UIUtils
LoadSet -.-> Crypto
LoadSet -.-> JFtp
SaveSet -.-> Settings
SaveSet -.-> Crypto
EventCollector -.-> EventProcessor
EventProcessor -.-> EventHandler
FtpEventHandler --> FtpClient
Dir --> BasicConnection
Dir --> DownloadList
DirCanvas --> Dir
DirCanvas -.-> UITool
DirCanvas -.-> PathChanger
DirCanvas -.-> GUIDefaults
DirCellRenderer --> ImageIcon
DirCellRenderer -.-> DirEntry
DirCellRenderer -.-> GUIDefaults
DirCellRenderer -.-> RemoteDir
DirCellRenderer -.-> LocalDir
DirComponent --> DirPanel
DirComponent -.-> ColoredCellRenderer
DirEntry -.-> HImage
DirEntry -.-> ImageIcon
DirEntry -.-> Image
DirLister --> BasicConnection
DirLister -.-> FtpConnection
DirLister -.-> FilesystemConnection

DirPanel --> DirEntry
DirPanel --> DownloadList
DirPanel --> BasicConnection
TableUtils --> TableCellRenderer
TableUtils --> TableColumnModel
TableUtils --> TableModel
TableUtils --> TableColumn

AppMenuBar --> JCheckBoxMenuItem
AppMenuBar -.-> Settings
AppMenuBar --> JFtp
AppMenuBar --> JMenu
AppMenuBar --> JMenuItem
AppMenuBar -.-> ProxyChooser
AppMenuBar -.-> AddBookmarks
AppMenuBar -.-> WebdavHostChooser
AppMenuBar -.-> SmbHostChooser
AppMenuBar -.-> SftpHostChooser
AppMenuBar -.-> NfsHostChooser
AppMenuBar -.-> LookAndFeel
AppMenuBar -.-> BookMarkItem
AppMenuBar -.-> UIUtils
AppMenuBar -.-> HttpDownloader
AppMenuBar -.-> AdvancedOptions
AppMenuBar -.-> BookmarkManager
AppMenuBar -.-> UIManager
AppMenuBar -.-> Displayer
AppMenuBar -.-> StartConnection

DownloadList --> ProgressBarList
DownloadList --> HImageButton
DownloadList -.-> ImageIcon
DownloadList --> HPanel
DownloadList -.-> AppMenuBar
DownloadList -.-> JFtp
DownloadList -.-> ConnectionHandler
DownloadList -.-> Log
DownloadList -.-> Transfer
DownloadList -.-> DataConnection
DownloadList -.-> UpdateDaemon
DownloadList -.-> DirEntry

DownloadQueue --> DefaultListModel
DownloadQueue --> QueueRecord
DownloadQueue --> BasicConnection
DownloadQueue --> HImageButton
DownloadQueue --> ConnectionHandler
DownloadQueue -.-> HPanel
DownloadQueue -.-> QueueRecord
DownloadQueue -.-> JFtp
DownloadQueue -.-> FtpConnection
DownloadQueue -.-> DataConnection
DownloadQueue -.-> JFileChooser
DownloadQueue -.-> File

LocalDir --> HImageButton
LocalDir --> DirCanvas
LocalDir --> DefaultListModel
LocalDir --> JScrollPane
LocalDir --> JPopupMenu
LocalDir --> JMenuItem
LocalDir --> DirEntry
LocalDir -.-> Settings
LocalDir -.-> TableUtils
LocalDir -.-> JFtp
LocalDir -.-> StringUtils
LocalDir -.-> DirLister
LocalDir -.-> BasicConnection
LocalDir -.-> FtpConnection
LocalDir -.-> RemoteCommand
LocalDir -.-> UITool
LocalDir -.-> NameChooser
LocalDir -.-> ZipFileCreator
LocalDir -.-> FilesystemConnection
LocalDir -.-> Log
LocalDir -.-> UpdateDaemon
LocalDir -.-> ZipEntry

LogFlusher -.-> Settings
LogFlusher -.-> JFtp

Properties --> HPanel

RemoteDir --> HImageButton
RemoteDir --> DirCanvas
RemoteDir --> DefaultListModel
RemoteDir --> DirEntry
RemoteDir -.-> FilesystemConnection
RemoteDir -.-> Settings
RemoteDir -.-> DirCellRenderer
RemoteDir -.-> JFtp
RemoteDir -.-> TableUtils
RemoteDir -.-> AdjustmentListener
RemoteDir -.-> FtpConnection
RemoteDir -.-> Sftp2Connection
RemoteDir -.-> DirLister
RemoteDir -.-> UITools
RemoteDir -.-> Creator

RemoteDir -.-> RemoteCommand
RemoteDir -.-> PathChanger
RemoteDir -.-> Log
RemoteDir -.-> UpdateDaemon
RemoteDir -.-> ResumeDialog

ResumeDialog --> DirEntry

StatusCanvas -.-> AppMenuBar
StatusCanvas -.-> GUIDefaults

StatusPanel --> StatusCanvas
StatusPanel --> HImageButton
StatusPanel --> JFtp
StatusPanel -.-> SmbHostChooser
StatusPanel -.-> SftpHostChooser
StatusPanel -.-> NfsHostChooser
StatusPanel -.-> WebdavHostChooser
StatusPanel -.-> HostChooser
StatusPanel -.-> Log


UIUtils -.-> Desktop

FileTransferable --> DataFlavor

HDesktopBackground -.-> Settings

HFrame -.-> Toolkit

HImage -.-> ClassLoader
HImage -.-> ImageIcon

HPanel -.-> GUIDefaults

DirEntry --> DirEntry

ProgressBarList -.-> ProgressbarItem


HostChooser --> HTextField
HostChooser --> HPanel
HostChooser --> HButton
HostChooser --> HFrame
HostChooser -.-> Settings

HostChooser -.-> Log
HostChooser -.-> HInsetPanel
HostChooser -.-> FtpURLConnection
HostChooser -.-> FtpConnection
HostChooser -.-> JFtp
HostChooser -.-> FilesystemConnection
HostChooser -.-> StartConnection
HostChooser -.-> HostList
HostChooser -.->FtpHost

NfsHostChooser --> HTextField
NfsHostChooser --> HPasswordField
NfsHostChooser --> HButton
NfsHostChooser -.-> HInsetPanel
NfsHostChooser -.-> HImage
NfsHostChooser -.-> ExternalDisplayer
NfsHostChooser -.-> NfsConnection
NfsHostChooser -.-> StartConnection

SftpHostChooser --> HTextField
SftpHostChooser --> HPasswordField
SftpHostChooser --> HButton
SftpHostChooser -.-> Settings
SftpHostChooser -.-> HInsetPanel
SftpHostChooser -.-> Sftp2URLConnection
SftpHostChooser -.-> Sftp2Connection
SftpHostChooser -.-> JFtp
SftpHostChooser -.-> Log

SmbHostChooser --> HTextField
SmbHostChooser --> HPasswordField
SmbHostChooser --> HButton
SmbHostChooser -.-> Settings
SmbHostChooser -.-> HPanel
SmbHostChooser -.-> HInsetPanel
SmbHostChooser -.-> NetworkInterface
SmbHostChooser -.-> Log
SmbHostChooser -.-> SmbConnection
SmbHostChooser -.-> StartConnection

WebdavHostChooser --> HTextField
WebdavHostChooser --> HPasswordField
WebdavHostChooser --> HButton
WebdavHostChooser -.-> HPanel
WebdavHostChooser -.-> JFtp

AddBookmarks --> HButton
AddBookmarks --> HComboBox
AddBookmarks --> HTextField
AddBookmarks --> HPasswordField
AddBookmarks -.-> JFtp
AddBookmarks -.-> System
AddBookmarks -.-> StringUtils
AddBookmarks -.-> StartConnection

AdvancedOptions --> HTextField
AdvancedOptions --> FtpConnection
AdvancedOptions -.-> HPanel
AdvancedOptions --> Settings

AutoRemover --> JFtp
BookMarkItem -.-> Settings
BookMarkItem -.-> UIUtils
BookMarkItem -.-> StartConnection

BookmarkManager -.-> JFtp
BookmarkManager -.-> Settings
BookmarkManager -.-> Log

Creator --> HTextField
Creator --> HButton
Creator --> BasicConnection

Displayer -.-> Log

HostList -.-> FtpHost
HttpBrowser -.-> Log
HttpDownloader --> HTextField
HttpDownloader --> HButton
HttpDownloader -.-> HttpTransfer

ImageViewer -.-> MediaTracker

LastConnections -.-> Settings
LastConnections -.-> JFtp

NameChooser --> HTextField
NameChooser --> HButton
NameChooser --> HPanel

PathChanger -->HTextField
PathChanger --> HButton

ProxyChooser --> HTextField
ProxyChooser --> HButton
ProxyChooser -.-> Settings

RemoteCommand -.-> HTextField
RemoteCommand -.->HButton

skinparam linetype ortho
@enduml