name: Java CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Invoke Maven
      run: mvn package
    - name: Upload Compiled JAR
      uses: actions/upload-artifact@v3.1.0
      with:
        name: jFTP
        path: target/*dependencies.jar
        retention-days: 7
